### ISSUE TITLE
why does it open the stub.py file inside of the gui.py

### ISSUE THREAD

**Issue by S3ntence** [f4kedre4lity/Blank-Grabber#10]
not saying its a stub js saying why

**Comment by noahmajors** [comment]
im not sure im understanding your question. 

gui.py is simply an interface for changing settings within stub.py, so it would need to be accessed by gui.py. Once you click build, the settings from gui.py are set into stub.py and are built into an exe.

**Comment by noahmajors** [comment]
stale
