### ISSUE TITLE
For it to run on someone else's pc do they only need the .exe file, because when I have tested it on a different pc from the one I build it on it hasn't worked. It has only worked on the pc I built it on.

### ISSUE THREAD

**Issue by ManLi091** [f4kedre4lity/Blank-Grabber#11]

**Comment by noahmajors** [comment]
yes, all they need is the 'Built.exe'. Sometimes it may need the victim to execute twice. Not sure of what the cause is, whether AV or something in the code, but as soon as I find it, i will be putting out a patch

**Comment by ManLi091** [comment]
ok, thanks
