### ISSUE TITLE
What to do with games (Files)

### ISSUE THREAD

**Issue by XZeeXx** [f4kedre4lity/Blank-Grabber#12]
i know 
![Screenshot 2023-08-11 134831](https://github.com/f4kedre4lity/Blank-Grabber/assets/142020743/5dd76f6e-d325-42b8-8376-868a257cbdc1)
how to use the cookies and that everything else. but i dont know how do you use the games file. im not sure what you do.

![image](https://github.com/f4kedre4lity/Blank-Grabber/assets/142020743/4f914c72-7831-46ea-a446-7699d8affbe4)

When i look in them their is nothing in their.

**Comment by noahmajors** [comment]
if you dont mind, please join the telegram group: https://t.me/+yR0KBvZ7GB40NWY1

we have guides on how to use most of the features. we are actively working on guides for any features that arent listed yet
