### ISSUE TITLE
How Do I remove this from my system (Windows 11)

### ISSUE THREAD

**Issue by Arthura0121** [f4kedre4lity/Blank-Grabber#16]
I accidentally opened the file while I was making it and it did its thing. Now I'm just wondering how do I remove it? Like Unblock AV websites and things like that?

**Comment by noahmajors** [comment]
Press WIN + R to open the Run Dialog. 

Type "shell:common startup" (without quotes) and press enter.

remove any file with a .scr file extension.

optionally, if you enabled discord injection, you will need to delete the discord client and reinstall it to remove the injection.

if you ran "block AV sites" on yourself, navigate to the Extras folder, open command prompt, and type "python unblock_sites.py"

**Comment by CoolGuy32325** [comment]
Still can't remove it python automatically closes
