### ISSUE TITLE
system still compromised

### ISSUE THREAD

**Issue by CreepyFungus29** [f4kedre4lity/Blank-Grabber#17]
I took the liberty of deleting everything out of my downloads folder (I extracted everything to downloads), then went to swap accounts, only to find my device still being pinged with it's own data. went into recycle bin and deleted everything, same thing, re-enabled my security settings, same thing. Where can I find this file, so I can actually remove it?

**Comment by noahmajors** [comment]
Press WIN + R to open the Run Dialog. 

Type "shell:common startup" (without quotes) and press enter.

remove any file with a .scr file extension.

optionally, if you enabled discord injection, you will need to delete the discord client and reinstall it to remove the injection.
