### ISSUE TITLE
can you guys make it less detected 

### ISSUE THREAD

**Issue by Quriqt** [f4kedre4lity/Blank-Grabber#19]
atm its detected by 11 av including microsoft av atleast make it so it dosnt get detected by microsoft av

**Comment by noahmajors** [comment]
im trying my best to reduce detections, but users, like you, keep tossing the stub into virustotal, which keeps it from remaining less detected. please consider using alternatives to virustotal to keep detections low. as for the current detections, im working on a major rewrite that could reduce some detections

**Comment by Quriqt** [comment]
ok
