### ISSUE TITLE
❤️ 

### ISSUE THREAD

**Issue by gumbobr0t** [f4kedre4lity/Blank-Grabber#22]
ay buddy im also developing my own stealer & i dont get how the final stub size for blank can be less than 10mb? mines about 70mb, even with upx, do you guys use a dropper or something?

also a really cool project!

**Comment by noahmajors** [comment]
because we made a base framework in which we can then add specific stealers to that framework. each stealer relies on the same base code with minor variations to pull different files of our choosing.

**Comment by gumbobr0t** [comment]
ahh i think i get it dang crazy work that you guys are doing
