### ISSUE TITLE
built.exe

### ISSUE THREAD

**Issue by MeowingDino** [f4kedre4lity/Blank-Grabber#24]
what do I do when I get to built.exe?

**Comment by noahmajors** [comment]
send it to victims (or yourself within a testing environment, since this project is for educational purposes only). once the exe is ran, you should receive the information shortly

**Comment by MeowingDino** [comment]
thx

**Comment by MeowingDino** [comment]
when i click built nothing happens

**Comment by noahmajors** [comment]
try running it again. if nothing happens once more, rebuild your payload with console set to debug and send your output
