### ISSUE TITLE
Archive password protected

### ISSUE THREAD

**Issue by cainanfoster** [f4kedre4lity/Blank-Grabber#26]
Good evening, 

I've built the executable and it's run its course. However, all data is saved in an archived format, a .rar, which is password protected. I've looked through the docs and cant find any info about this.

**Comment by gumbobr0t** [comment]
blank123
@cainanfoster

**Comment by gumbobr0t** [comment]
however, blank and his kids are all weird

**Comment by noahmajors** [comment]
sorry for the late response. the archive password is 'blank' by default. if that does not work for you, check the config.json file located in the project directory after building to find your password value.
