### ISSUE TITLE
it doesn't open the blank grabber it didn't work

### ISSUE THREAD

**Issue by thanashaPRO5** [f4kedre4lity/Blank-Grabber#29]
say this Traceback (most recent call last):
  File "C:\Users\thana\Desktop\Blank-Grabber-main\Blank Grabber\gui.py", line 12, in <module>
    import customtkinter as ctk
ModuleNotFoundError: No module named 'customtkinter'

**Comment by noahmajors** [comment]
pip install customtkinter

**Comment by thanashaPRO5** [comment]
> pip install customtkinter

yes now say this  python: can't open file 'C:\\Users\\thana\\Desktop\\Blank-Grabber-main\\Blank Grabber\\gui.py': [Errno 2] No such file or directory

**Comment by noahmajors** [comment]
This usually means that you haven’t actually unzipped the project yet.

**Comment by thanashaPRO5** [comment]
bro its work but no to windows 11

**Comment by noahmajors** [comment]
It works just fine on Windows 11, with no bugs. I can say this because I develop and test it on Windows 11…
