### ISSUE TITLE
Doesnt Work

### ISSUE THREAD

**Issue by NBDMatr1x** [f4kedre4lity/Blank-Grabber#32]
Blank grabber doesnt work for me on other computers.

**Comment by noahmajors** [comment]
sometimes it can hang. try having the user run it as admin, or run it again after 5 minutes. this is a known issue and is being looked into, while i find the cause.

**Comment by NBDMatr1x** [comment]
it is running with admin ill try the running it after 5 mins and get back to you

**Comment by NBDMatr1x** [comment]
tried it and still didnt work for me
