### ISSUE TITLE
"Educational purposes"

### ISSUE THREAD

**Issue by UnpracticalCode** [f4kedre4lity/Blank-Grabber#5]
![Screenshot_20230807_005412_Discord](https://github.com/f4kedre4lity/Blank-Grabber/assets/122434248/360d88fe-31d4-477b-b970-e9fb0ad576b6)

**Comment by m1daz** [comment]
I think his local idaho police will find it sooo educational they will begin educating him about the american law!

**Comment by UnpracticalCode** [comment]
![Screenshot_20230808_004032_GitHub.png](https://github.com/f4kedre4lity/Blank-Grabber/assets/122434248/54e75f82-a180-44b1-b271-a497c459e717)

**Comment by noahmajors** [comment]
> I think his local idaho police will find it sooo educational they will begin educating him about the american law!

I don’t think it’s very wise to just assume that my “readme” contains accurate information. At the end of the day it’s just text on a screen. Good luck finding me in Idaho😘

**Comment by real-fbdn** [comment]
> > I think his local idaho police will find it sooo educational they will begin educating him about the american law!
> 
> I don’t think it’s very wise to just assume that my “readme” contains accurate information. At the end of the day it’s just text on a screen. Good luck finding me in Idaho😘

W bro W
