### ISSUE TITLE
Quit

### ISSUE THREAD

**Issue by m1daz** [f4kedre4lity/Blank-Grabber#6]
Dont close issues... we never stop.

Were working on a tool to identify all types of malware just based on the stub, and were writing software to automatically delete all webhooks all over youtube. We already have on

**Comment by m1daz** [comment]
Also... great opsec noahmajors... great indeed. As a programmer for 8 years youve never made mistakes. Never made a fiver and forgot about it, never freelanced or anything... never did anything that you might have forgotten about.

**Comment by noahmajors** [comment]
oh no, its like i just said. random name, random state. as if i would use my full name on github to develop malware. you can quit glazing over me too, since this is purely for educational purposes 💀
